pipeline {

    agent any

    options {
        timestamps()
        disableConcurrentBuilds()
    }

    stages {

        stage('Checkout') {
            steps {
                echo 'Checking out Terraform repository...'

                checkout scm
            }
        }


        stage('Terraform Version') {
            steps {
                sh '''
                    terraform version
                '''
            }
        }


        stage('Terraform Init') {
            steps {
                echo 'Initializing Terraform...'

                sh '''
                    terraform init
                '''
            }
        }


        stage('Terraform Validate') {
            steps {
                echo 'Validating Terraform configuration...'

                sh '''
                    terraform validate
                '''
            }
        }


        stage('Terraform Plan') {
            steps {
                echo 'Creating Terraform execution plan...'

                sh '''
                    terraform plan \
                    -out=tfplan
                '''
            }
        }




        stage('Terraform Apply') {
            steps {
                echo 'Applying Terraform infrastructure...'

                sh '''
                    terraform apply \
                    -auto-approve \
                    tfplan
                '''
            }
        }


        stage('Terraform Output') {
            steps {
                echo 'Terraform outputs:'

                sh '''
                    terraform output
                '''
            }
        }
    }


    post {

        success {
            echo '''
            ========================================
            Infrastructure deployment SUCCESS
            ========================================
            '''
        }

        failure {
            echo '''
            ========================================
            Infrastructure deployment FAILED
            ========================================
            '''
        }

        always {
            archiveArtifacts(
                artifacts: 'tfplan',
                allowEmptyArchive: true
            )
        }
    }
}